services:
  my-proxy:
    image: atom0827/my-proxy:latest
    container_name: my-proxy
    restart: unless-stopped
    network_mode: host  # 使用宿主机网络
    environment:
      - PORT=9090
      - HTTP_PROXY=http://****:*******@192.168.31.128:7890
      - HTTPS_PROXY=http://****:*******@192.168.31.128:7890
      - NO_PROXY=localhost,127.0.0.1